// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0lU-FXFKAZRa14afuF9ZEKQYYZPszMs',
    appId: '1:522111336049:web:ad60d719373c77658525d0',
    messagingSenderId: '522111336049',
    projectId: 'beggar-online',
    authDomain: 'beggar-online.firebaseapp.com',
    storageBucket: 'beggar-online.firebasestorage.app',
    measurementId: 'G-V5NC1X57M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiMEztFNzCfFBot8FFSmd98zdzp89JY5M',
    appId: '1:522111336049:android:ede30c4d739bd81e8525d0',
    messagingSenderId: '522111336049',
    projectId: 'beggar-online',
    storageBucket: 'beggar-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZmS3GcFv4o1Dror1GDZEk0gph9VXRXKM',
    appId: '1:522111336049:ios:da0888aff5a61f228525d0',
    messagingSenderId: '522111336049',
    projectId: 'beggar-online',
    storageBucket: 'beggar-online.firebasestorage.app',
    iosBundleId: 'com.globevik.beggar',
  );

}